<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Ardalis.SmartEnum.SystemTextJson" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Database\Shared.Database.csproj" />
    <ProjectReference Include="..\Domain\Shared.Domain.csproj" />
    <ProjectReference Include="..\Extensions\Shared.Extensions.csproj" />
  </ItemGroup>

</Project>
