// <auto-generated />
using System;
using Detour.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Detour.Database.Migrations
{
    [DbContext(typeof(DetourDbContext))]
    partial class DetourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("detour")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Detour.Domain.ApiKeys.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_api_keys_user_id");

                    b.ToTable("api_keys", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Circles.CirclePlace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ClientPlaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_place_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_meters");

                    b.HasKey("Id")
                        .HasName("pk_circle_places");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_circle_places_owner_id");

                    b.HasIndex("GroupId", "CreatedAt")
                        .HasDatabaseName("ix_circle_places_group_id_created_at");

                    b.HasIndex("GroupId", "OwnerId", "ClientPlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_circle_places_group_id_owner_id_client_place_id");

                    b.ToTable("circle_places", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Circles.PlaceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ClientPlaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_place_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp_ms");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_place_events");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_place_events_user_id");

                    b.HasIndex("GroupId", "TimestampMs")
                        .HasDatabaseName("ix_place_events_group_id_timestamp_ms");

                    b.ToTable("place_events", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Friendships.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HighUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("high_user_id");

                    b.Property<Guid>("LowUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("low_user_id");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_friendships");

                    b.HasIndex("HighUserId")
                        .HasDatabaseName("ix_friendships_high_user_id");

                    b.HasIndex("LowUserId", "HighUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_friendships_low_user_id_high_user_id");

                    b.ToTable("friendships", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Groups.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_groups_owner_id");

                    b.HasIndex("Kind", "OwnerId")
                        .HasDatabaseName("ix_groups_kind_owner_id");

                    b.ToTable("groups", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Groups.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsSharing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_sharing");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_group_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_members_user_id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_members_group_id_user_id");

                    b.ToTable("group_members", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Groups.MemberFix", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp_ms");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_member_fixes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_member_fixes_user_id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_member_fixes_group_id_user_id");

                    b.ToTable("member_fixes", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Places.SavedPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ClientPlaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_place_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_places");

                    b.HasIndex("UserId", "ClientPlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_places_user_id_client_place_id");

                    b.ToTable("saved_places", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Routes.SharedRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ClientRouteId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_route_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id")
                        .HasName("pk_shared_routes");

                    b.HasIndex("FromUserId")
                        .HasDatabaseName("ix_shared_routes_from_user_id");

                    b.HasIndex("ToUserId", "CreatedAt")
                        .HasDatabaseName("ix_shared_routes_to_user_id_created_at");

                    b.HasIndex("ToUserId", "FromUserId", "ClientRouteId")
                        .IsUnique()
                        .HasDatabaseName("ix_shared_routes_to_user_id_from_user_id_client_route_id");

                    b.ToTable("shared_routes", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Traces.Trace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line");

                    b.Property<string>("LineHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("line_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_traces");

                    b.HasIndex("UserId", "LineHash")
                        .IsUnique()
                        .HasDatabaseName("ix_traces_user_id_line_hash");

                    b.ToTable("traces", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Traces.TrackPoint", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp_ms");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("LeanDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("lean_degrees");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double?>("SpeedKmh")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kmh");

                    b.HasKey("UserId", "TimestampMs")
                        .HasName("pk_track_points");

                    b.ToTable("track_points", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_meters");

                    b.Property<long?>("EndTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("end_time_ms");

                    b.Property<double?>("MaxGForce")
                        .HasColumnType("double precision")
                        .HasColumnName("max_g_force");

                    b.Property<string>("Mode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<long>("StartTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("start_time_ms");

                    b.Property<double>("TopSpeedKmh")
                        .HasColumnType("double precision")
                        .HasColumnName("top_speed_kmh");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("UserId", "StartTimeMs")
                        .IsUnique()
                        .HasDatabaseName("ix_trips_user_id_start_time_ms");

                    b.ToTable("trips", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Users.BadgeAward", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BadgeId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("badge_id");

                    b.Property<long>("EarnedAtMs")
                        .HasColumnType("bigint")
                        .HasColumnName("earned_at_ms");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_badge_awards");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique()
                        .HasDatabaseName("ix_badge_awards_user_id_badge_id");

                    b.ToTable("badge_awards", "detour");
                });

            modelBuilder.Entity("Detour.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdministrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_administrator");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<bool>("ShareFog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("share_fog");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("subject");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("citext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_subject");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "detour");
                });

            modelBuilder.Entity("Detour.Domain.ApiKeys.ApiKey", b =>
                {
                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_users_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Circles.CirclePlace", b =>
                {
                    b.HasOne("Detour.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_circle_places_groups_group_id");

                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_circle_places_users_owner_id");
                });

            modelBuilder.Entity("Detour.Domain.Circles.PlaceEvent", b =>
                {
                    b.HasOne("Detour.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_events_groups_group_id");

                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_place_events_users_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Friendships.Friendship", b =>
                {
                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("HighUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_users_high_user_id");

                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("LowUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_users_low_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Groups.Group", b =>
                {
                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_groups_users_owner_id");
                });

            modelBuilder.Entity("Detour.Domain.Groups.GroupMember", b =>
                {
                    b.HasOne("Detour.Domain.Groups.Group", null)
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Groups.MemberFix", b =>
                {
                    b.HasOne("Detour.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_fixes_groups_group_id");

                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_member_fixes_users_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Places.SavedPlace", b =>
                {
                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_places_users_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Routes.SharedRoute", b =>
                {
                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_shared_routes_users_from_user_id");

                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shared_routes_users_to_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Traces.Trace", b =>
                {
                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_traces_users_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Traces.TrackPoint", b =>
                {
                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_points_users_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Trips.Trip", b =>
                {
                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trips_users_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Users.BadgeAward", b =>
                {
                    b.HasOne("Detour.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_badge_awards_users_user_id");
                });

            modelBuilder.Entity("Detour.Domain.Users.User", b =>
                {
                    b.OwnsOne("Detour.Domain.Users.RiderStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<double>("BestCoveragePercent")
                                .HasColumnType("double precision")
                                .HasColumnName("stats_best_coverage_percent");

                            b1.Property<double>("LongestTripMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("stats_longest_trip_meters");

                            b1.Property<double?>("MaxLeanDegrees")
                                .HasColumnType("double precision")
                                .HasColumnName("stats_max_lean_degrees");

                            b1.Property<int>("MunicipalitiesVisited")
                                .HasColumnType("integer")
                                .HasColumnName("stats_municipalities_visited");

                            b1.Property<double>("TopSpeedKmh")
                                .HasColumnType("double precision")
                                .HasColumnName("stats_top_speed_kmh");

                            b1.Property<double>("TotalDistanceMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("stats_total_distance_meters");

                            b1.Property<int>("TripCount")
                                .HasColumnType("integer")
                                .HasColumnName("stats_trip_count");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "detour");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("Detour.Domain.Groups.Group", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
